spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/quality_layer?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&allowMultiQueries=true&allowPublicKeyRetrieval=true&useSSL=false&zeroDateTimeBehavior=convertToNull
    username: root
    password: xxx
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      database: 0
      password:            # 你的Redis没设密码就留空；设了密码就填 "你的密码"
      timeout: 10s

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.quality.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true

logging:
  level:
    com.quality: debug
    org.springframework: debug
    org.springframework.jdbc: debug
    org.mybatis: debug

server:
  port: 8081